default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  host: localhost
  username: postgres
  password: postgres

development:
  <<: *default
  database: Creasic_development

test:
  <<: *default
  database: Creasic_test

production:
  <<: *default
  database: Creasic_production
  username:
  password:
